name: autodeploy
"on":
    push:
        branches:
            - master
    workflow_dispatch: {}
env:
    ACR_RESOURCE_GROUP: RGForAppService
    AZURE_CONTAINER_REGISTRY: acrworkflow1692811819315
    CLUSTER_NAME: AKScluster
    CLUSTER_RESOURCE_GROUP: RGForAppService
    CONTAINER_NAME: image-workflow-1692811819315
    DEPLOYMENT_MANIFEST_PATH: |
        manifests/deployment.yaml
        manifests/service.yaml
jobs:
    buildImage:
        permissions:
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: azure/login@v1
              name: Azure login
              with:
                client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C4EAA6E3B7AB4EBF8FA0C04D32D8D0C8 }}
                subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_50B31A6695EF4667BACC760171259672 }}
                tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B67C1C1B5FA3493CA65F41F57B2D1665 }}
            - name: Build and push image to ACR
              run: az acr build --image ${{ env.CONTAINER_NAME }}:${{ github.sha }} --registry ${{ env.AZURE_CONTAINER_REGISTRY }} -g ${{ env.ACR_RESOURCE_GROUP }} -f Dockerfile ./
    deploy:
        permissions:
            actions: read
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        needs:
            - buildImage
        steps:
            - uses: actions/checkout@v3
            - uses: azure/login@v1
              name: Azure login
              with:
                client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C4EAA6E3B7AB4EBF8FA0C04D32D8D0C8 }}
                subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_50B31A6695EF4667BACC760171259672 }}
                tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B67C1C1B5FA3493CA65F41F57B2D1665 }}
            - uses: azure/use-kubelogin@v1
              name: Set up kubelogin for non-interactive login
              with:
                kubelogin-version: v0.0.25
            - uses: azure/aks-set-context@v3
              name: Get K8s context
              with:
                admin: "false"
                cluster-name: ${{ env.CLUSTER_NAME }}
                resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
                use-kubelogin: "true"
            - uses: Azure/k8s-deploy@v4
              name: Deploys application
              with:
                action: deploy
                images: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ github.sha }}
                manifests: ${{ env.DEPLOYMENT_MANIFEST_PATH }}
                namespace: namespace-workflow-1692811819315
